cloud-barista/cb-larva

poc-cb-net/cb-network.go
It's required because the previous URL sometimes takes time or fails to get public IP.
=> Change URL getting public IP

poc-cb-net/cmd/agent/agent.go, poc-cb-net/cmd/server/server.go, poc-cb-net/internal/app/pitcher-and-catcher.go, poc-cb-net/internal/cb-network/cb-network.go
- Replace "watch > get host network information > put" with "get > watch with rev > get host network information > compare and swap"
- Remove channel value
- Add mutext lock to securely update the networking rule
- Add sleep before starting PitcherAndCatcher application
- Perform linting
=> Improve the network update mechanism

poc-cb-net/cmd/agent/agent.go, poc-cb-net/internal/app/pitcher-and-catcher.go, poc-cb-net/internal/cb-network/cb-network.go
- Add mutex lock to the networking rule update part
- Check host ID to set cb-nework by using networking rule
- By compare-and-swap (CAS), efficiently put host network information and also update the networking rule
- Relocate go routines to the beginning section
- Perform linting
=> Improve a configuration mechanism of networking rule

Dockerfile, poc-cb-net/cmd/agent/agent.go, poc-cb-net/cmd/server/server.go, poc-cb-net/internal/app/pitcher-and-catcher.go, poc-cb-net/internal/cb-network/cb-network.go, poc-cb-net/internal/file/file.go
- Read configs from two paths
- Load configs from the path ./configs/ (for container-based execution)
- Load configs from the path ../../configs/ (for source code based execution)
- Add a Dockerfile to build a container image for the cb-network controller
- Add WaitGroup to wait for all goroutines to finish (necessary for detached mode container)
- Add the file package including Exist() to check if the file exists or not
=> Containerize the cb-network controller

poc-cb-net/cmd/agent/agent.go, poc-cb-net/cmd/server/server.go, poc-cb-net/web/public/index.html
- Get CLADNet's configuration information by CLADNet ID
- Use a network CIDR block to assign an IP for a host(VM)
=> Utilize CLADNet's configuration information created by users

poc-cb-net/cmd/agent/agent.go, poc-cb-net/cmd/server/server.go, poc-cb-net/configs/template)config.yaml, poc-cb-net/internal/cb-network/data-objects/config.go, poc-cb-net/scripts/build-agent.sh, poc-cb-net/scripts/prepare-to-build-agent.sh
- Add cb_network, cladnet_id, host_id to config.yaml and config.go
- Add demo_app, is_run to config.yaml and config.go
- Improve a script to build and run the cb-network agent
- Update the cb-network agent's mechnism of agent.go
=> Improve the agent's config and mechanism to assign VM ID

poc-cb-net/internal/cb-network/cb-network.go
- Change "https://ifconfig.co/" to "https://api.ipify.org?format=text"
- Add the other candidates as comments
=> Change the source of a public IP API

poc-cb-net/scripts/build-and-run-agent-in-the-background.sh
- Redirect stdout and stderr to /dev/null (nothing to print)
- Add comment for the nohup command
=> improve nohup command to run agent in background

scripts/Kubernetes/2.setup-K8s-master.sh
To generalize the script to deploy Kubernetes master, 
this PR Provide an option to set network env variable from parameter.
With this PR, default value for env variables are as follows,
- `DEFAULT_NETWORK_INTERFACE`=`cbnet0`
- `DEFAULT_POD_NETWORK_CIDR`=`10.77.0.0/16`
You can change setting by providing named parameters. (`-i` for `NETWORK_INTERFACE`, `-c` for `POD_NETWORK_CIDR`)
e.g., `./2.setup-K8s-master.sh -i eth0 -c 10.77.0.0/16`
If the script can not detect given network interface from `ifconfig`, EXIT from the script.
- Ex: Output01
son@son:~/go/src/github.com/cloud-barista/cb-larva/scripts/Kubernetes$ **./2.setup-K8s-master.sh** 
```
cbnet0: error fetching interface information: Device not found
[Network env variables for this Kubernetes cluster installation] …
```
=> Provide an option to set network env variable from parameter

.github/workflows/lint-on-push.yml
- Change installation method from "go get" to "install.sh" script
=> Install golangci-lint by a script

.github/workflows/build-on-pull-request.yml, .github/workflows/lint-on-push.yml
Updated the Go version on workflows from 1.15.x to 1.16.x
Files having the change
- build-on-pull-request.yaml
- lint-on-push.yml
=> Updated the Go version from 1.15.x to 1.16.x

poc-cb-net/cmd/service/cladnet-service.go, poc-cb-net/cmd/test-client/test-client.go, poc-cb-net/internal/network-helper/network-helper.go
Resolve #142, #149
- Add getDescendingOrderedKeysOfMap() and update related code blocks because the ordering is not supported for the Go map
- Fix bug related to the assignment of a recommended IPv4 private address space
=> Add descending order func for map and fix a bug

poc-cb-net/scripts/1.deploy-cb-network-agent.sh, poc-cb-net/scripts/2.re-deploy-cb-network-agent.sh
- Download the cb-network agent execution file (binary file)
- Generate configuration yaml files
- Create a script to run cb-network agent for Linux service
- Create a service file for cb-network agent
- Start the cb-network agent service by `systemctl`
- Enable the cb-network agent service by `systemctl`
- Use re-deploy-cb-network-agent.sh when the agent is updated
=> Deploy the cb-network agent as a Linux service

poc-cb-net/cmd/controller/controller.go, poc-cb-net/internal/network-helper/network-helper.go
- Change the range of IP address candidate
- Round up (Ceiling) a log scale of needed prefix
=> Fix bad allocation of address space and IP address

poc-cb-net/cmd/test-client/demo-client.go, poc-cb-net/scripts/1.deploy-cb-network-agent.sh, poc-cb-net/scripts/2.re-deploy-cb-network-agent.sh, poc-cb-net/scripts/get-and-run-agent.sh
- From `https://github.com/cloud-barista/cb-larva/releases/download/v0.0.6/agent`
to `https://github.com/cloud-barista/cb-larva/releases/download/v0.0.7/agent`
=> Update the binary link for the cb-network agent

.github/workflows/lint-on-push.yml
fix #173 
- Delete whitespaces at `poc-cb-net/archive/**`
- Add `poc-cb-net/pkg/api/**` to paths-ignore
=> Ignore protos and protobuffers from lint test workflow

.github/workflows/build-on-pull-request.yml, .github/workflows/lint-on-push.yml, poc-cb-net/cmd/admin-web/admin-web.go, poc-cb-net/cmd/agent/agent.go, poc-cb-net/cmd/controller/controller.go, poc-cb-net/internal/app/pitcher-and-catcher.go, poc-cb-net/internal/cb-network/cb-network.go, poc-cb-net/internal/cb-network/model/host-network-information.go, poc-cb-net/internal/cb-network/model/network-interface.go, poc-cb-net/internal/cb-network/model/networking-rule.go, poc-cb-net/internal/command/command.go, poc-cb-net/internal/etcd-key/etcd-key.go, poc-cb-net/internal/network-helper/network-helper.go, poc-cb-net/web/public/index.html
- Re-structure the cb-network agent to control it remotely
- Change network-related naming convention
- Newly create command package to use a command in the same manner and also to add new command easily
=> Control the agents remotely

poc-cb-net/cmd/admin-web/admin-web.go, poc-cb-net/cmd/agent/agent.go, poc-cb-net/internal/cb-network/cb-network.go, poc-cb-net/internal/command/command.go, poc-cb-net/web/public/index.html
- Include the status test in the control command as the `check-connectivity`
- Provide `resume` and `suspend` commands to control cb-network agents remotely
- Improve the overall `cb-network` package for this
=> Control the cb-network agent from the remote

poc-cb-net/internal/cb-network/cb-network.go, poc-cb-net/internal/network-helper/network-helper.go
- Change the related sections
- Remove the existing `IsPrivateIP()` from the `nethelper` package
=> Replace the existing IsPrivateIP() with `net.IP.IsPrivate()`

.gitignore, poc-cb-net/cmd/agent/agent.go, poc-cb-net/cmd/test-client/config/template-config.yaml, poc-cb-net/config/template-config.yaml, poc-cb-net/internal/cb-network/cb-network.go, poc-cb-net/internal/cb-network/model/config.go, poc-cb-net/internal/cb-network/model/host-network-information.go, poc-cb-net/internal/etcd-key/etcd-key.go, poc-cb-net/internal/secret-util/secret-util.go
- Create `sectuil` package
- Add secret exchange and update mechanism
- Encrypt and decrypt messages between hosts (i.e., the cb-network agents)
- Test and debug the end-to-end encryption
- Do lint
- Add comments
=> Add end to end encryption

poc-cb-net/cmd/agent/agent.go, poc-cb-net/cmd/controller/controller.go, poc-cb-net/internal/cb-network/cb-network.go, poc-cb-net/internal/etcd-key/etcd-key.go, poc-cb-net/scripts/1.deploy-cb-network-agent.sh, poc-cb-net/scripts/2.re-deploy-cb-network-agent.sh
- Synchonize the other hosts' networking rule with distributed lock
- Put host network information by each host
- Allocate or update the network rule for a host with distributed lock
- Add new etcd key for distributed-lock
=> Fix abnormal networking rule sychronization

poc-cb-net/cmd/agent/agent.go, poc-cb-net/cmd/controller/controller.go, poc-cb-net/internal/cb-network/model/peer.go
- Add `configuring` state
- Add `syscall.SIGHUP` and `syscall.SIGABRT` for graceful shutdown
- Update graceful shutdown processes
=> Improve the cb-network agent state tracking

poc-cb-net/cmd/test-client/perf-eval-client/perf-eval-client.go
- Set the interval more clearly
- Compare the deadline and the next start time
- Improve logging
=> Update a client for performance evaluation

poc-cb-net/cmd/admin-web/admin-web.go, poc-cb-net/cmd/agent/agent.go, poc-cb-net/cmd/controller/controller.go, poc-cb-net/cmd/service/service.go, poc-cb-net/pkg/cb-network/cb-network.go, poc-cb-net/web/public/index.html
**The cb-network controllers** don't keep the peer information and the networking rule where the peer participates. It is stored and managed in `etcd` cluster. On the other hand, **the cb-network agent** has its own information (i.e., this peer).
So, I'm trying to move functions from the controller to the agent and simplify the related logic. I expect it's beneficial to reduce the number of I/Os and the amount of data to `etcd`.
=> Reduce complexity to update networking rule

poc-cb-net/cmd/agent/agent.go
Remove the peer state check on an update of the networking rule
When a peer changes, it is pushed to all peers (i.e., they are watching). In this case, changes made by other peers should always be applied to the networking rule.
=> Fix peer state update

poc-cb-net/cmd/admin-web/admin-web.go, poc-cb-net/cmd/agent/agent.go, poc-cb-net/cmd/controller/controller.go, poc-cb-net/cmd/service/service.go
- Log etcd keys with debug level before requesting
- Log etcd responses with trace level
- Log a function's start and end with debug level
- Log the elapsed time for locking
=> Improve logging

poc-cb-net/config/template-log_conf.yaml, poc-cb-net/scripts/1.deploy-cb-network-agent.sh, poc-cb-net/scripts/2.re-deploy-cb-network-agent.sh, poc-cb-net/scripts/build-and-run-agent-in-the-background.sh, poc-cb-net/scripts/build-and-run-agent.sh, poc-cb-net/scripts/deploy-the-released-cb-network-agent.sh, poc-cb-net/scripts/get-and-run-agent.sh, poc-cb-net/scripts/redeploy-the-released-cb-network-agent.sh
from "./log/cblogs.log" to "/var/log/cblogs.log"
It's necessary for the cb-network system to integrate with the distributed logging system (i.e., Elastic Stack) in a loosely-coupled manner.
=> Chagne the log file path

poc-cb-net/cmd/admin-web/admin-web.go, poc-cb-net/cmd/agent/agent.go, poc-cb-net/cmd/controller/controller.go, poc-cb-net/cmd/service/service.go
- Add logs for etcd IO
- Log bytes on message instead of fields
=> Improve logging for etcd IO bytes
