cloud-barista/cb-larva

- poc-cb-net/1.env-setup-script.sh
- poc-cb-net/2.cbnet-setup-script.sh
* 1.env-setup-script.sh: Apt packages are installed.
* 2.cbnet-setup-script.sh: A pair of virtual ethernet interfaces is created.
* 2.cbnet-setup-script.sh: eth0 and veth0 are added to cbnet0(bridge).
* 2.cbnet-setup-script.sh: DNS is set up.
> Add scripts to create a pair of virtual ethernet interfaces

- poc-cb-net/2.cbnet-setup-script.sh
- Change variables from lower case to upper case
- Remove unnecessary spaces
> Refactor source codes

- poc-cb-net/agent/main.go
- poc-cb-net/server/main.go
MQTT-based cb-net server and agent are added.
> Add mqtt based cb net agent and server

- poc-cb-net/README.md
Update Readme for En with minor modifications.
^____^
> Update Readme for En with minor modifications

- poc-cb-net/archive/test.go
- poc-cb-net/cb-network.go
- poc-cb-net/cmd/agent/agent.go
- poc-cb-net/cmd/server/server.go
- poc-cb-net/internal/pitcher-and-catcher.go
- Add error handling section after write() function
- Drop unnecessary use of the blank identifier
- Remove an empty body in an if or else branch
> Resolve lint errors

- .gitignore
- poc-cb-net/cmd/server/server.go
- poc-cb-net/internal/data-objects/config-mqtt-broker.go
- Add poc-cb-net/configs/mqtt-broker.json
- Untrack poc-cb-net/configs/ by adding gitignore to protect sensitive information
- Create ConfigMQTTBroker and its loader on poc-cb-net/internal/data-objects
> Add MQTTBroker config and loader for it

- .github/workflows/build-on-pull-request.yml
- Run the workflow on a pull request to master or devleop
> Add a workflow on build-on-pull-request.yml

- poc-cb-net/cmd/agent/agent.go
- poc-cb-net/cmd/server/server.go
- poc-cb-net/internal/data-objects/config-mqtt-broker.go
- Add a config of MQTTBroker
- Add a loader for MQTTBroker config
- Replace the hardcoded MQTT Broker endpoint with the endpoint created by the config
> Remove dependency on public MQTT Broker

- poc-cb-net/README.KR.md
- poc-cb-net/README.md
- Update README.md (EN)
- Update README.KR.md (KR)
> Add how to add config of mqtt broker

- .github/workflows/build-on-pull-request.yml
- .github/workflows/lint-on-push.yml
- markdown, gitignore, and LICENSE files are ignored
> Ignore updates of some files in workflow

- go.mod
- go.sum
- poc-cb-net/archive/test.go
- poc-cb-net/cmd/agent/agent.go
- poc-cb-net/cmd/server/server.go
- poc-cb-net/configs/template)config.yaml
- poc-cb-net/internal/app/pitcher-and-catcher.go
- poc-cb-net/internal/cb-network/cb-network.go
- poc-cb-net/internal/cb-network/data-objects/config.go
- poc-cb-net/internal/cb-network/data-objects/networking-rule.go
- poc-cb-net/web/public/index.html
- Replace the MQTT client mechanisms with Websocket protocol and the etcd client mechanisms
- Update configs and the related template to add AdminWeb(Websocket) configuration
- Watch networking rule in the etcd cluster and send it to AdminWeb
- Add group-id to networking-rule for efficient data exchange and visualization mechanism
- Perform linting
> Improve adminweb

- Dockerfile
- poc-cb-net/cmd/agent/agent.go
- poc-cb-net/cmd/server/server.go
- poc-cb-net/internal/cb-network/cb-network.go
- poc-cb-net/internal/cb-network/data-objects/networking-rule.go
- Improve Dockerfile
- Change the read mechanism of config files
> Improve the containerization code of the cb-network controller

- poc-cb-net/cmd/agent/agent.go
- poc-cb-net/cmd/server/server.go
- poc-cb-net/internal/cb-network/cb-network.go
- poc-cb-net/internal/cb-network/data-objects/networking-rule.go
- Read configs from the current directory for the production(or for the containerization)
- Read configs from the project directory for the development
> Read configs from the current directory or project directory

- Dockerfile
- poc-cb-net/scripts/build-agent.sh
- Newly add a script to build agent
- Add comments on Dockerfile for better understanding
> Add a script to build agent.go and comments on Dockerfile

- poc-cb-net/cmd/server/server.go
- poc-cb-net/web/public/index.html
- Improve a mechanism to handle and show multiple CLADNets in frontend
- Rename titles AdminWeb for better understanding
- Get and send the networking rules for each CLADNet
> Handle multi-CLADNet's networking rule

- poc-cb-net/scripts/build-and-run-agent-in-the-background.sh
> Run agent in background by nohup

- poc-cb-net/cmd/agent/agent.go
- poc-cb-net/cmd/server/server.go
- Create watchStatusTestSpecification(), configurationInformationHandler() and testSpecificationHandler() to functionalize relavant code block
> Reduce function complexity

- poc-cb-net/scripts/build-and-run-agent-in-the-background.sh
- poc-cb-net/scripts/build-and-run-agent.sh
- Change a specific branch to the main branch
> Change the default branch to run and build cb-network in scripts

- scripts/Kubernetes/3.setup-K8s-master.sh
Fix bug in setup-K8s-master.sh
Fix typo.
> Fix bug in setup-K8s-master.sh

- .gitignore
- poc-cb-net/cmd/admin-web/admin-web.go
- poc-cb-net/cmd/controller/controller.go
- Copy controller.go to admin-web.go
- Remove admin-web source code from controller.go
- Remove controller source code from admin-web.go
- Update gitignore to ignore admin-web, the execution file
> Separate AdminWeb from the cb-network controller

- go.mod
- go.sum
- poc-cb-net/cmd/controller/controller.go
- Create assignIPAddressTohost() function
- Rearrange the related source code
> Modularize a code block to assign an IP address to host

- poc-cb-net/internal/cb-network/model/available-ipv4-private-address-spaces.go
- poc-cb-net/internal/network-helper/network-helper.go
- Add initMap() to initialize map variables
- Add GetAvailableIPv4PrivateAddressSpaces()
- Add AvailableIPv4PrivateAddressSpaces struct
> Support available IPv4 private address spaces

- poc-cb-net/internal/cb-network/model/available-ipv4-private-address-spaces.go
- poc-cb-net/internal/network-helper/network-helper.go
- Put AvailableIPv4PrivateAddressSpaces in network-helper package
- Initialize IPs and networks for private networks in init()
> Update network-helper package

- poc-cb-net/cmd/controller/controller.go
Resolve #137 
- Create a distributed lock
- Aquire a lock before get a networking rule
- Release the lock after put the networking rule
> Protect networking rules by locking

- poc-cb-net/cmd/controller/controller.go
> Add getIpv4AddressSpace()

- poc-cb-net/internal/network-helper/network-helper.go
Resolve #149 
- Calculate a prefix according to the number of hosts
- Get an IPv4 address space from available Pv4 private address spaces
> Add recommendAnIPvAddressSpace()

- go.mod
- go.sum
- poc-cb-net/cmd/test-client/test-cb-tumblebug-apis/test-cb-tumblebug-apis.go
- poc-cb-net/cmd/test-client/test-client.go
[Running log]
Elapsed time: 5m31.5474901s
```bash
2021/11/18 15:12:15.256682 WARN RESTY Using Basic Auth in HTTP mode is not secure, use HTTPS
Error: <nil>
Time: 679µs
Body: {"message":"API server of CB-Tumblebug is alive"}
Sleep 5 sec ( _ _ )zZ
2021/11/18 15:12:20.261979 WARN RESTY Using Basic Auth in HTTP mode is not secure, use HTTPS
Error: <nil>
Time: 2m25.5254892s
Body: {"id":"mcis01","name":"mcis01","status":"Running-4(4/4)","statusCount":{"countTotal":4,"countCreating":0,"countRunning":4,"countFailed":0,"countSuspended":0,"countRebooting":0,"countTerminated":0,"countSuspending":0,"countResuming":0,"countTerminating":0,"countUndefined":0},"targetStatus":"Running","targetAction":"Create","installMonAgent":"no","label":"custom tag","systemLabel":"","description":"Made in …
```
> Replace `jsonparser` package with `gjson` one for alignment

- poc-cb-net/cmd/test-client/test-cb-tumblebug-apis/test-cb-tumblebug-apis.go
- poc-cb-net/cmd/test-client/test-client.go
- scripts/Kubernetes/1.setup-environment-and-tools.sh
- scripts/Kubernetes/2.setup-K8s-master.sh
- Add deployKubernetesCluster() function to show an usecase easily
- Update existing scripts
- Improve log messages
> Add `deployKubernetesCluster()` function to the `test-client`

- poc-cb-net/cmd/admin-web/admin-web.go
- poc-cb-net/cmd/agent/agent.go
- poc-cb-net/cmd/test-client/test-client.go
Add query syntax to the `test-client`
- Press the 'ENTER' key to continue
- Ask to try to deploy a single Kubernetes cluster across multi-clouds
- Add MCIS clean-up
- Ask to clean up MCIS
> Add query syntax to the `test-client`

- poc-cb-net/cmd/test-client/test-client.go
- scripts/Kubernetes/4.deploy-and-access-Kubernetes-dashboard.sh
- scripts/Kubernetes/5.deploy-and-access-Guestbook.sh
- scripts/Kubernetes/6.deploy-and-access-Weave-Scope.sh
- Kubernetes dashbaord
- Guestbook
- Weave Scope
> Add scripts for 3 applications

- poc-cb-net/cmd/test-client/test-client.go
- scripts/Kubernetes/4.deploy-and-access-Kubernetes-dashboard.sh
- scripts/Kubernetes/5.deploy-and-access-Guestbook.sh
- scripts/Kubernetes/6.deploy-and-access-Weave-Scope.sh
- Update scripts related to Kubernetes
- Improve shortcut commands
- Create the interactWithMasterVM() due to complexity (cyclo)
> Finalize test-client

- poc-cb-net/cmd/controller/controller.go
**It would support multiple cb-network controllers without a scheduler.**
Each host (VM) records the dynamic changes of its local network. For example, VM1 can record its local network changes twice and VM2 can record its local network change once. In any order, the cb-network controller must distinguish those and only need to deal with one of them.
**To distinguish each sporadic update in multiple data sets, I have developed a mechanism with the lease and compare-and-swap (CAS). The cb-network controllers try to lease a temporal key by CAS.** (It's like acquiring a workload (i.e., handling of data update).).** 
- **A cb-network controller acquires the temporal key** if the key doesn't exist.
- **The other cb-network controllers will pass to acquire** the key because the key was already …
> Support multiple cb-network controllers

- poc-cb-net/README.KR.md
- poc-cb-net/README.md
- Improve README
- Test overall components
> Improve README for release

- .github/workflows/build-on-pull-request.yml
- .github/workflows/lint-on-push.yml
- go.mod
- go.sum
- poc-cb-net/cmd/agent/agent.go
- poc-cb-net/internal/cb-network/cb-network.go
- Replace tun package
- Upgrade Go version to 1.17+
- Enhance logging
> Configure TUN by `syscall` instead of `water` tun package

- .gitattributes
- .golangci.yml
- poc-cb-net/cmd/controller/controller.go
- poc-cb-net/internal/cb-network/cb-network.go
- Add `.gitattributes` to align the line endings (i.e., lf)
- Increase `gocyclo` min-complexity to 16
- Minor update by `gostaticcheck`
In addition, set the following in VSCode's settings.json to resolve compile error issue
```json
"go.toolsEnvVars": {
"GOOS": "linux"
}
```
> Change the environmental factors of the project

- go.mod
- go.sum
- poc-cb-net/cmd/admin-web/admin-web.go
- poc-cb-net/cmd/agent/agent.go
- poc-cb-net/cmd/controller/controller.go
- poc-cb-net/internal/app/pitcher-and-catcher.go
- poc-cb-net/internal/cb-network/cb-network.go
- poc-cb-net/internal/cb-network/model/host-rule.go
- poc-cb-net/internal/cb-network/model/networking-rule.go
- poc-cb-net/web/public/index.html
- Subdivide the data structure
- Create a struct, HostRule
- Store and control the networking rule based on HostRule (not networking rule chunk)
> Improve the control mechanism of cb-network system

- poc-cb-net/web/public/index.html
> Rearrange the admin-web UI

- poc-cb-net/cmd/agent/agent.go
- poc-cb-net/web/public/index.html
- Change the ping test method (One host pings all other hosts)
- Handle duplicated test results on the visualizer side
> Update network status check

- poc-cb-net/cmd/agent/agent.go
- poc-cb-net/cmd/controller/controller.go
- poc-cb-net/internal/etcd-key/etcd-key.go
- Improve etcd key structure 
- Improve secret initialization method
> Patch secret sync

- poc-cb-net/cmd/agent/agent.go
- poc-cb-net/internal/cb-network/cb-network.go
- Close listen connection
- Change log level from fatal to debug to return a function normally
> Fix resume failure

- poc-cb-net/cmd/agent/agent.go
- poc-cb-net/internal/cb-network/model/peer.go
- Add `suspending` status
- Shutdown gracefully by signals
> Track the status of cb-network agents

- poc-cb-net/cmd/admin-web/admin-web.go
- poc-cb-net/cmd/controller/controller.go
- poc-cb-net/pkg/cb-network/cb-network.go
- Handle EOF issue
- Update logging
- Fix a wrong etcd key related to the lease
> Specify the size of buffer when writing a packet

- poc-cb-net/cmd/agent/agent.go
- poc-cb-net/cmd/controller/controller.go
- poc-cb-net/cmd/service/cladnet-service.go
- poc-cb-net/cmd/test-client/demo-client.go
- poc-cb-net/cmd/test-client/test-rest-call/test-rest-call.go
- poc-cb-net/pkg/cb-network/cb-network.go
- poc-cb-net/pkg/cb-network/model/networking-rule.go
- poc-cb-net/pkg/secret-util/secret-util.go
- Update `test-rest-call.go`
- Update `demo-client.go`
- Update logging to check the project root
> Replace `stub` with struct in REST section

- poc-cb-net/cmd/agent/agent.go
- poc-cb-net/cmd/controller/controller.go
- poc-cb-net/pkg/cb-network/cb-network.go
- poc-cb-net/pkg/cb-network/model/peer.go
- poc-cb-net/pkg/command/command.go
- poc-cb-net/web/public/index.html
- Change peer state
- Change control command from the remote
- Change function name
- Add const variables for peer state and control command from the remote
> Change peer state and command to be network-like

- poc-cb-net/README.KR.md
- poc-cb-net/README.md
- poc-cb-net/cmd/agent/agent.go
- poc-cb-net/cmd/controller/controller.go
- poc-cb-net/cmd/test-client/config/template-config.yaml
- poc-cb-net/config/template-config.yaml
- poc-cb-net/pkg/cb-network/cb-network.go
- poc-cb-net/pkg/cb-network/dynamic-subnet-configuration.go
- poc-cb-net/pkg/cb-network/model/config.go
- poc-cb-net/pkg/cb-network/model/host-network-information.go
- poc-cb-net/pkg/cb-network/model/network-status.go
- poc-cb-net/pkg/cb-network/model/networking-rule.go
- poc-cb-net/pkg/cb-network/model/peer.go
- poc-cb-net/scripts/1.deploy-cb-network-agent.sh
- poc-cb-net/scripts/2.re-deploy-cb-network-agent.sh
- poc-cb-net/scripts/build-and-run-agent-in-the-background.sh
- poc-cb-net/scripts/build-and-run-agent.sh
- poc-cb-net/scripts/get-and-run-agent.sh
- poc-cb-net/web/public/index.html
- Add the name field to distinguish ID and name
- Be able to set the network interface name and tunneling port
- Add ConfigureHostID() for a unique host ID
> Update peer configuration

- poc-cb-net/scripts/1.deploy-cb-network-agent.sh
> Update a script to deploy cb-network agent

- .gitignore
- Dockerfile-service
- build.sh
- poc-cb-net/Makefile
- poc-cb-net/README.KR.md
- poc-cb-net/README.md
- poc-cb-net/cmd/admin-web/admin-web.go
- poc-cb-net/cmd/service/service.go
- poc-cb-net/cmd/test-client/config/template-config.yaml
- poc-cb-net/config/template-config.yaml
- poc-cb-net/pkg/cb-network/model/config.go
- poc-cb-net/scripts/1.deploy-cb-network-agent.sh
- poc-cb-net/scripts/2.re-deploy-cb-network-agent.sh
- poc-cb-net/scripts/build-and-run-agent-in-the-background.sh
- poc-cb-net/scripts/build-and-run-agent.sh
- poc-cb-net/scripts/get-and-run-agent.sh
> Release v0.0.12

- poc-cb-net/cmd/admin-web/admin-web.go
- poc-cb-net/cmd/agent/agent.go
- poc-cb-net/cmd/controller/controller.go
- poc-cb-net/cmd/service/service.go
- poc-cb-net/pkg/cb-network/model/networking-rule.go
- "git" package is not found when running a container
Ref: https://cloud-barista.slack.com/archives/CJQ7575PU/p1650330154118099
> Update initializing configs

- poc-cb-net/cmd/agent/agent.go
- poc-cb-net/cmd/test-client/perf-eval-client/perf-eval-client.go
- poc-cb-net/web/public/index.html
- Add self connectivity check
- Update latency if it exists on cb-network admin-web
- Remove filter to write all test data
- Improve logging
> Improve connectivity checking and performance evaluation

- poc-cb-net/cmd/test-client/perf-eval-client/perf-eval-client.go
- Make a function by using the duplicated code blocks
- Correct the wrong test cycle
> Reduce the function complexity of perf-eval-client.go

- scripts/Kubernetes/1.setup-environment-and-tools.sh
- scripts/Kubernetes/2.setup-K8s-master.sh
- From master node setup to all node setup
> Relocate a code block to handle `kubeadm init` issue

- poc-cb-net/cmd/admin-web/admin-web.go
- poc-cb-net/cmd/agent/agent.go
- poc-cb-net/cmd/controller/controller.go
- poc-cb-net/cmd/service/service.go
- poc-cb-net/pkg/cb-network/cb-network.go
- Set cb-network default values on the constructor
- Specify ID to each cb-network component for logging
> Identify components on logging

- .golangci.yml
- go.mod
- poc-cb-net/cmd/service/service.go
- poc-cb-net/cmd/test-client/check-response-time-of-cb-tumblebug-api/check-response-time-of-cb-tumblebug-api.go
- poc-cb-net/cmd/test-client/demo-client/demo-client.go
- poc-cb-net/cmd/test-client/perf-eval-client/perf-eval-client.go
- poc-cb-net/cmd/test-client/test-cb-tumblebug-apis/test-cb-tumblebug-apis.go
- poc-cb-net/cmd/test-client/test-rest-call/test-rest-call.go
- poc-cb-net/pkg/cb-network/model/config.go
- Add package name on the import section (typecheck)
> Fix lint errors

- poc-cb-net/cmd/agent/agent.go
모든 피어 동기화의 시작과 끝을 로깅하기 위한 PR 입니다.
> Log the start and end of all peer synchronization

- go.mod
- go.sum
> Update go mod to apply cb-log formatter updates
